language: node_js
node_js:
  - 8
cache: yarn
script:
  - yarn lint
  - yarn build
deploy:
  provider: s3
  region: us-east-1
  bucket: $(node config ProjectFQDomain)
  acl: public_read
  cache_control: "max-age=31536000"
  local_dir: dist
  skip_cleanup: true
  on:
    branch:
      - master
      - bjacobel/ssr
    condition: $(node aws/utils bucketExists) = "true"
after_deploy:
  - node aws/utils invalidate "index.html dem/index.html rep/index.html ind/index.html"
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
